### ISSUE TITLE
Persist the state of the "Include titles" checkbox accross sessions

### ISSUE THREAD

**Issue by gyje** [alct/export-tabs-urls#1]
I have a suggestion , Add a setting option, include or not include a title .

**Comment by alct** [comment]
Hello,

Thank you for your feedback.

Could you explain further what you have in mind? (there is a checkbox on the main popup that lets you include titles or not)

**Comment by gyje** [comment]
If I need a title every time, I don't want to click the include title every time.

**Comment by alct** [comment]
That would be useful indeed. I'll give it a shot when I have some time :)

**Comment by JimboMac** [comment]
The "Limit to current page" check box went missing today. After I Un-installed and re-installed the extension the check box is still missing.

**Comment by alct** [comment]
Hello @JimboMac ,

Thank you for your feedback. I'm pretty sure that it is not a bug but a feature, the "limit to the current window" checkbox is only displayed when there are actually several windows. Does the problem occur when several windows are open?

If it is actually a bug, could you please create a new issue with information about your Firefox and ETU version?

**Comment by E3V3A** [comment]
Any progress on this enhancement?

**Comment by alct** [comment]
> Any progress on this enhancement?

I have started to work on it.

**Comment by alct** [comment]
Implemented in 0.2.0, see 5239d04218942ae7f7539b4b1b541fa1311d3aa9
