### ISSUE TITLE
Add {window-id} and {container} special blocks to custom format

### ISSUE THREAD

**Issue by yphastos** [alct/export-tabs-urls#10]
It would be nice to be able to export the windows and/or container* names for each tab.
*For containers I mean the ones in the official [container add-on](https://addons.mozilla.org/es/firefox/addon/multi-account-containers/) provided by mozilla

I tend to have my windows organized for what I do on each, and also use several containers among them. So it would be extremely useful to be able to list the window "names" (e.g. 1,2,3, or A,B,C), and the container names (e.g. Personal, Work, Dev...)

Also it would be useful to export such options as a header for "groups" of windows/containers, e.g.:

> window 1 - Personal
> 
> tab 1 title
> url1
> 
> tab 2 title
> url2

------

Or adding it to each tab, e.g.

> window 1 - Personal - tab 1 title
> url 1
> 
> window 1 - Personal - tab 1 title
> url 2
> 
> window 1 - Work - tab 3 title
> url 3
> 
> ...etc

-----

**Comment by alct** [comment]
Hello, thank you for your suggestion.

In both cases, it would best implemented by adding new special blocks to the "Custom format" option.

Yet, unless I am mistaken, an extension can not access information about **containers**. Therefore I am afraid it can not be implemented for the time being. This could be useful indeed.

As for the **window name**, Firefox windows do not have a name but an id. The best we could get would be an `int` (e.g. 1, 2, 3,...). I fail to see how this could be of any help given that windows can already be exported individually by using the "Limit to current window" feature.

**Comment by yphastos** [comment]
Thanks, as for the window name, I already assumed there is no "real" name other than a number identifier, but i have no problem with that. Window 1, window 2 would suffice.

As for:

> I fail to see how this could be of any help given that windows can already be exported individually by using the "Limit to current window" feature.

The reason is because we could save **all tabs from all windows** in a single step, and being able to **distinguish** tabs from each window, instead of having to export manually for each separate window, specially when we have a bunch of windows instead of just a couple.

I use the add-on as a sort of a _light_ session managing for tabs. I don´t care about session cookies or similar session specific stuff, so a simple list of tabs is enough. Thus, having such exported tabs a bit more organized (grouping by windows) would be very useful to me.

**Comment by alct** [comment]
Given that it requires almost zero change to the code and that it does not interfere with the UX (it is a complementary option when creating a custom format), it has been impleted in 0.2.7, see https://github.com/alct/export-tabs-urls/commit/27fd6eb9d0d727c9f12ed5c4e4f524651b272f89.

Thank you for your suggestion! :+1:
