### ISSUE TITLE
Fix tab filtering feature

### ISSUE THREAD

**Issue by 0xRustlang** [alct/export-tabs-urls#12]
Hello

Thank you for this great addon.
the tab filtering feature don't have any form that we can put things that we want it to filter.
I use Firefox 67.
May you please fix this?

Here is the screenshot:
https://upload.disroot.org/r/WFzjg1lj#DdHNIhjsi8pD0+3jg4PI4mLa5ZjG7a+zLkVTFGZPevo=

Thanks

**Comment by alct** [comment]
Hello,

Thank you for your feedback !

That is problematic indeed. Could you please take a screenshot of the Export Tabs URLs (ETU) popup (and make sure that the "Enable tabs filtering" checkbox is checked in the options)?

**Comment by 0xRustlang** [comment]
Here you are:
https://upload.disroot.org/r/R7CBi35O#FQDjSj0hB7mPTvf6E+XhwnvG4yxvXqmkqf14fota2zA=

I checked and tab filtering was checked in options.

**Comment by alct** [comment]
In the popup, what happens if you click on "Filter tabs" and type "rclone" for instance?

**Comment by 0xRustlang** [comment]
Oh, Really Sorry
I didn't noticed it there before.
I had thought that filter means that we add some characters in settings so they get removed from the result.

I will create another issue for that as a suggestion.
Regards
