### ISSUE TITLE
Support for Chromium

### ISSUE THREAD

**Issue by smaragdus** [alct/export-tabs-urls#14]
Do you have plans to port **Export Tabs URLs** extension to Chromium-based browsers?

I prefer to use extensions which are available for both Chromium and Firefox thus achieving similar functionality in both browsers so I would appreciate if **Export Tabs URLs** is available for Chromium too.

If you don't use Chromium-based browsers or you have other reasons not to port the extension I won't be disappointed- I am just asking.

**Comment by alct** [comment]
> Do you have plans to port Export Tabs URLs extension to Chromium-based browsers?

No. It is a political choice rather than a technical one.

Chrome(ium) has a track record of being hostile towards other browser vendors. So much so that it is now absolutely dominating the web browser ecosystem. The lack of substantial competition is not healthy for the open web.

As a long time advocate for the open web and standards, I refuse to contribute to this situation by developing tools that improve the user experience on Chrome(ium) and thus decrease - if only marginally - users will to try other web browsers.

**Comment by smaragdus** [comment]
@alct 

I understand your attitude. I have several browsers ([Cent Browser](https://www.centbrowser.com/), [Iridium](https://iridiumbrowser.de/), [Vivaldi](https://vivaldi.com/), [Iceweasel](https://sourceforge.net/projects/libportable/), [Pale Moon](https://www.palemoon.org/)) and I am not completely pleased with any of them. About the Chromium ones- Vivaldi is not open source and it tracks users and for me it has already become bloated, Cent Browser is not open source either and it also tracks users but I find it lighter and generally better than Vivaldi, Iridium is open source and de-Googled but it is not that handy to use. Iceweasel is custom Firefox build which can easily be made portable. Pale Moon has the advantage to be able to to use old powerful XUL extensions (most of them- in compatibility mode). I agree that the browser market is heading towards total monopoly and this is detrimental to the web yet in my opinion Google is not the only one to blame for the current dismal situation- Mozilla is losing market share because it does not respect its user base removing feature after feature (I lost track of all the removed features, for me the removal of RSS support was atrocious). I have also tested [Falkon](https://www.falkon.org/) and [Otter](https://otter-browser.org/) and I was not impressed but these projects are maintained by very small teams and the development is slow, in the long run these projects may be doomed but at least they deserve some praise for respecting user's privacy.

I respect your decision and I will close this issue. I am not in the least in love with Chromium- it is less customizable than Firefox and it also removes feature after feature. For example preventing individual extensions from updating is now close to impossible, previously I could edit `manifest.json` files (`"update_url":` line) to disable updates of certain extensions but this no longer works. Another 'feature' I find horrible is that Chromium no longer allows to install CRX files that are not listed in their walled garden, 'load unpacked extension' is a workaround painful to use. More- Google is now attacking ad-blocking extensions by replacing webRequest API with limited declarativeNetRequest API- for me this is outrageous and I suppose (and hope) that this may lead to loss of market share. Excuse me for the long and off-topic post.

Regards
