### ISSUE TITLE
Windows: EOL are not properly rendered in Notepad

### ISSUE THREAD

**Issue by Ryo501** [alct/export-tabs-urls#2]
I'm having a bug with the export as file function, when I export to a file all the URLs are concatenated together with no spaces.

Also I was wondering if you could add a checkbox that grabs the group tabs of just the current window if more than one firefox window exists.

**Comment by alct** [comment]
Hello,

Thank you for your feedback.

> I'm having a bug with the export as file function, when I export to a file all the URLs are concatenated together with no spaces.

Could you please provide me with some info about your Operating System, your Firefox version, the Export Tabs URLs version, and the software used to open the file?

**Comment by Ryo501** [comment]
OS: Windows 10
Firefox: 60.0
Export Tabs URLs: 0.1.9
Software: notepad

Edit:
If I use notepad++ or sublime Text it works just fine. I believe it is an issue with how microsoft notepad handles the newline character from the textarea element. I downloaded your source files to see if I could fix it and I believe if you add the code below between lines 85 and 86 in your popup.js file it should fix it.

`list = list.replace(/\n/g, "\r\n")`

**Comment by alct** [comment]
> OS: Windows 10
> Firefox: 60.0
> Export Tabs URLs: 0.1.9
> Software: notepad

Thank you for the info.

Does it only occur when titles are not included?

And could please also check whether this problem occurs when you click on the "Copy to clipboard button" and paste it into Notepad?

> I believe it is an issue with how microsoft notepad handles the newline character from the textarea element

Well, I thought that I fixed this issue a couple of months ago: the format is specified [L55](https://github.com/alct/export-tabs-urls/blob/master/popup/popup.js#L55) and [L59](https://github.com/alct/export-tabs-urls/blob/master/popup/popup.js#L59) and none of them use the "\n" notation. That might as well be related to how EOLs are handled inside textareas.

[Microsoft has recently announced that they will finally fix this EOL handling bug](https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/) in future releases but I will investigate this further in order to get a proper fix in the meantime.

**Comment by Ryo501** [comment]
It happens both with and without titles, the "Copy to clipboard button" and pasting does work.

I have tested the line of code in my second post and it works, at least for me, with and without titles in notepad, notepad++, and sublime text.

Edit:
When I inspected the exported files, with original code, in notepad++ with the setting show all characters, I noticed that the "\r"(Carriage return) does not show up. I believe the textarea does not use that character, it will display the "\r" character inside the textarea (which is why copy / paste works), but it seems to remove the character when getting the value of the textarea.

**Comment by alct** [comment]
Thank you again for your feedback.

> When I inspected the exported files, with original code, in notepad++ with the setting show all characters, I noticed that the "\r"(Carriage return) does not show up. I believe the textarea does not use that character, it will display the "\r" character inside the textarea (which is why copy / paste works), but it seems to remove the character when getting the value of the textarea.

This inconsistency is weird indeed. As stated above, I want to investigate further to avoid releasing a temporary fix and risk cascade the problem onto new features.

From my tests (extension v0.1.9):

| OS | Include titles  | Action | Output EOLs |
| --- | --- | --- | --- |
| Linux | no | Copy button | \n |
| Linux | yes | Copy button | \n |
| Linux | no | Export button | \n |
| Linux | yes | Export button | \n |
| Windows | no | Copy button | \r\n |
| Windows | yes | Copy button | \r\n |
| Windows | no | Export button | \n |
| Windows | yes | Export button | \n |

**Comment by alct** [comment]
I just pushed a fix https://github.com/alct/export-tabs-urls/commit/8156d3bf10b1c10419fd3817baced9fa7ea129bb and uploaded an updated version to AMO.

Rather then blindly forcing `\r\n` when the export function is used (which would result in inconsistent behaviour on every OS but Windows), the fix detects the operating system and only overwrites the EOLs if needed.

Thank you again for your feedback :+1: 

Tests (extension v0.1.10):

| OS | Include titles  | Action | Output EOLs |
| --- | --- | --- | --- |
| Linux | no | Copy button | \n |
| Linux | yes | Copy button | \n |
| Linux | no | Export button | \n |
| Linux | yes | Export button | \n |
| Windows | no | Copy button | \r\n |
| Windows | yes | Copy button | \r\n |
| Windows | no | Export button | \r\n |
| Windows | yes | Export button | \r\n |
