### ISSUE TITLE
Add a feature to mark tabs 

### ISSUE THREAD

**Issue by CarpeDiemKopi** [alct/export-tabs-urls#23]
e.g. with color and export only the marked tabs into the clipboard. If you are working with very many open tabs you can gather the picked out ones while the working time. 

There would be even more possibilities if one could mark different subject areas in different colors and export for each color into the clipboard.

**Comment by alct** [comment]
Hello,

Thank you for your feedback.

You can already mark tabs about a specific topic for export (sort of) using the built-in filtering feature. It works across windows and hundreds of tabs, RegExp can be used to tailor the results to virtually any specific needs. Furthermore, the list in the popup can be edited right before export.

I want to keep ETU as effective and simple as possible, therefore I am unfortunately unlikely to add any feature related to manual point and click selection of tabs.
