### ISSUE TITLE
Add support for command-line params

### ISSUE THREAD

**Issue by CarpeDiemKopi** [alct/export-tabs-urls#25]
so you can call Export Tabs URLs from the command line.

**Comment by alct** [comment]
Hello,

Thank you for your feedback.

Is it something that you have already seen implemented in another extension?

I am not aware of features in Firefox allowing to pilot extensions from the CLI  (even in Firefox headless mode). Do not hesitate to provide me with information if I am wrong.

**Comment by alct** [comment]
Closing this issue given the lack of updates after a month.
(do not hesitate to comment with new info, I'll gladly re-open it)
