### ISSUE TITLE
Bug: several instances of firefox => always the same list in export-tabs-urls

### ISSUE THREAD

**Issue by CarpeDiemKopi** [alct/export-tabs-urls#27]
but one expects the list confined to the instance. 

For a different behavior,  you should use an extra button/switch i.e. new feature.

**Comment by alct** [comment]
Hello,

Thank you for your feedback.

Could you please provide me with some info about your Operating System, your Firefox versions (do you open several instances of the same version ?) and the Export Tabs URLs version?

**Comment by alct** [comment]
Closing this issue given the lack of updates after a month.
(do not hesitate to comment with new info, I'll gladly re-open it)
