### ISSUE TITLE
Add an option to handle non-http(s) locations

### ISSUE THREAD

**Issue by E3V3A** [alct/export-tabs-urls#6]
The Tab export, seem to ignore non-http/s locations, such as `file://` etc.

**Comment by alct** [comment]
Hello,

This is a [feature](https://github.com/alct/export-tabs-urls/blob/master/popup/popup.js#L96). Most users will rarely deal with non-http(s) locations, I wanted to avoid them the burden of having to deal with weird (about:config,...) URLs in their exports or a useless/cryptic checkbox in the popup.

This being said, this is indeed a feature that could be useful to some more advanced users.

I plan to add an option to include all URLs in the future. This will come after #1 .

**Comment by alct** [comment]
Implemented in 0.2.0, see 5239d04218942ae7f7539b4b1b541fa1311d3aa9
