### ISSUE TITLE
Add a feature to filter tabs within the popup

### ISSUE THREAD

**Issue by keeganwitt** [alct/export-tabs-urls#9]
If you added a filter like [this plugin](https://addons.mozilla.org/en-US/firefox/addon/export-tabs-urls-and-titles/) has, I think that'd make this plugin the most feature rich in the category.
![image](https://user-images.githubusercontent.com/64612/53700586-e87d0280-3dc1-11e9-8cb7-e43da27526fa.png)
Although this might be a little more complicated to support than it was for the other plugin, since you also support titles. For my use case, just filtering URL would be sufficient.

**Comment by alct** [comment]
Hello, thank you for your interest in ETU.

This feature would have far reaching consequences on the UX. If anything, I think that the added value of ETU compared to other similar add-ons resides in its UX: I have tried, and hopefully managed, to keep it clean and straightforward. My answer is neither a "yes" nor a "no", I want to take the time to think about how such features could be implemented.

In the meantime, could you please share your workflow/usecase? Why do you save your tabs in general? What do you do with the backups? When do you sort/filter the tabs and why?

I would greatly appreciate if you could answer these few questions and more broadly enlighten me with your user experience.

**Edit:** the URL that you have provided doesn't seem to be the right one

**Comment by keeganwitt** [comment]
I tend to use this plugin to move tabs between browsers more than anything else.  I'm an unapologetic tabaholic, and this would allow me to move just the tabs I need over.

Honestly, what I do in that Firefox extension I mentioned, even more often than filtering, is to grab the URLs of tabs to copy over in that text box (so I can select specific tabs).
![image](https://user-images.githubusercontent.com/64612/54577720-44a37180-49d3-11e9-84eb-6bb7cb0a1327.png)
Which is something your plugin already provides.  The filtering, for me is just nice to occasionally have for times I've really gotten too many tabs.  It'd help limit what you have to select through with your cursor.

As for sorting, I've never used the sorting feature of that plugin so far, nor have I used the saving feature so far (I'd use Session Buddy or OneTab for that purpose).

**Comment by keeganwitt** [comment]
Corrected links
https://addons.mozilla.org/en-US/firefox/addon/urls-list/
https://github.com/moritz-h/urls-list

**Comment by keeganwitt** [comment]
Wait a minute -- I opened the issue against the wrong project!  I meant to open it against https://github.com/vincepare/CopyAllUrl_Chrome, since I wanted the functionality of this plugin in Chrome.

/Facepalm

**Comment by keeganwitt** [comment]
Actually, I just realized the bigger problem is not being able to import from clipboard.  It might be that these two plugins are serving different goals.

**Comment by alct** [comment]
I have been thinking about the **filtering feature** and am starting to believe that it could, indeed, be useful (and not disruptive for users who do not need it). I came up with some mockups.

If implemented, this is what the feature might look like (the ribbon is just there to denote the beta channel).

![image](https://imgs.be/5ca7c35f-483.png)

Rather than having another visual form element for the search/filter field, it is visually integrated within the textarea. When the filter is used, the counter provides feedback about the number of results.

As for the **import feature**, that is something that I have been thinking about form the start but have not figured out how to integrate UX-wise yet. Properly parsing valid URLs is not a trivial task when they are potentially mixed with user custom formatting.

**Comment by alct** [comment]
Implemented in 0.2.3, see https://github.com/alct/export-tabs-urls/commit/cfc06ab4390310075c64fc6ac65ea4e2eff9bb16 (make sure to enable the feature in ETU settings)

**Comment by keeganwitt** [comment]
Sweet!  One note: it was enabled by default when I installed the addon, not sure if that's what you intended.

**Comment by alct** [comment]
It is on purpose :)

On the one hand, I find the feature really useful (even more so thanks to RegExp) and want to give new users a glimpse of its usefulness. On the other, thanks to the way it is integrated, it should not be disruptive for users who do not need it.

**Comment by keeganwitt** [comment]
Yea, I think that's totally reasonable.  I was just double checking since you said "(make sure to enable the feature in ETU settings)"

**Comment by alct** [comment]
Thank you for your vigilance :) :+1:
